# Generated by Django 4.1.4 on 2023-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_campus_code_user_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
