# Generated by Django 4.1.4 on 2023-06-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='faculty_code',
        ),
    ]
