# Generated by Django 4.1.4 on 2023-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='innovation_media/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='InnovationMedia',
        ),
    ]
