# Generated by Django 4.1.4 on 2023-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0002_innovation_media_delete_innovationmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='youtube_link',
            field=models.TextField(null=True),
        ),
    ]
