# Generated by Django 4.1.4 on 2023-02-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0003_innovation_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='innovation',
            name='youtube_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
