# Generated by Django 4.1.4 on 2023-06-09 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation', '0004_remove_innovation_youtube_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='media',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='youtube_code',
        ),
        migrations.AddField(
            model_name='innovation',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='innovations/'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innovation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='innovation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Innovator',
        ),
    ]
