# Generated by Django 4.1.4 on 2023-06-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_member_role_remove_project_donor_and_more'),
        ('innovation', '0005_remove_innovation_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.project'),
        ),
    ]
