# Generated by Django 4.1.4 on 2023-07-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0006_innovation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='reason_for_denial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='response',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
