# Generated by Django 4.1.4 on 2023-06-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
