# Generated by Django 4.1.4 on 2023-06-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='publication/'),
        ),
    ]
